name: deploy-to-swarm
on:
    push:
        branches:
            - 'master'
    pull_request:
        branches:
            - 'master'
jobs:
    echo:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Echo
              run: echo 'hello world'